/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.Diario;
import java.util.ArrayList;
/**
 *
 * @author Luis
 */
public class DiarioDialog extends javax.swing.JDialog {

  Diario diarioD = new Diario().getInstance(); //creamos un atributo de instancia que sea una instancia de diario
                                                        //con la que se trabaja en el juego y cuya informaión se muestra en esta ventana
    
    
    /**
     * Creates new form DiarioDialog
     */
    public DiarioDialog(java.awt.Frame parent) { //EN TEORIA SOLO ES UN PARAMETRO PERO LUEGO USA MODAL
        super(parent,true);//invoca al constructor de la clase JFrame de la que depende y
//establece el modal a true, es decir, hasta que no se cierre esta ventana no se devuelve el
//control a la ventana vista principal.
        initComponents(); //invoca un metodo que se crea por defecto y
        //que inicializa las variables asociadas a los componenetes creados en la pestaña de diseño
        setLocationRelativeTo(null); //establece el centro de la pantalla como el lugar para colocar la ventana
       // while(!Diario.getInstance().getEventos().isEmpty()){
        Diario.getInstance().leerEvento();
      //  Diario.setText(diario.leerEvento());
      
      
      //  }
      //  TextEventos.setText("Eventos"); //generamos un texto con todos los eventos pendientes
        this.TextEventos.setText(Diario.getInstance().leerEvento());
        this.setVisible(true);
        repaint();
        revalidate();
    }  
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Eventos = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextEventos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eventos.setText("Eventos");
        getContentPane().add(Eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        TextEventos.setEditable(false);
        TextEventos.setColumns(20);
        TextEventos.setRows(5);
        jScrollPane2.setViewportView(TextEventos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 400, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_OKActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiarioDialog dialog = new DiarioDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eventos;
    private javax.swing.JButton OK;
    private javax.swing.JTextArea TextEventos;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
