/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.Jugador;
import civitas.Casilla;
import java.util.ArrayList;
import civitas.CasillaCalle;
        
/**
 *
 * @author Luis
 */
public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */
   private  Jugador jugador; //atributo jugador de la clase jugador
    public JugadorPanel() {
        initComponents();
    }
   
    
   private void rellenaPropiedades (ArrayList<CasillaCalle> lista) {
 // Se elimina la información antigua
 propiedadesPanel.removeAll();
 // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
 for (CasillaCalle t : lista) {
 PropiedadPanel vistaPropiedad = new PropiedadPanel();
 vistaPropiedad.setPropiedad(t);

 propiedadesPanel.add(vistaPropiedad);
 vistaPropiedad.setVisible(true);
 }
 // Se fuerza la actualización visual del panel propiedades y del panel del jugador
 repaint();
 revalidate();
}
    void setJugador(Jugador jugador){ //metdo que recibe como argumento un objeto de la clase jugador 
        this.jugador=jugador; // asociar lo que recibe como argumento con el atributo jugador
        //nombre.setText("Nombre: "); //dar valor al metodo setText a todas las variables textfield
       // saldo.setText("Saldo: ");
        
       // Espc.setText("Especulador: ");
      //  Casilla.setText("Número de casilla actual: ");
       String especulador; //esto lo he puesto por el pavo
        nombre.setText(jugador.getNombre()); //dar valor al metodo setText a todas las variables textfield
        saldo.setText(Float.toString(jugador.getSaldo()));
       if(jugador.esEspeculador()){
           especulador = "Si";
       }
       else {
           especulador = "No";
       }
        this.Especulador.setText(especulador); //Boolean.toString(jugador.esEspeculador())
      //  casilla.setText(Integer.toString(jugador.getCasillaActual()));
       
        rellenaPropiedades(this.jugador.getPropiedades());  //se llama a este mtodo enviando como argumento las propiedades del juegador actual
        //repaint(); ////----------------------------------eEEEEEEEEEEEEEEEKJGS´KTJGW´KR
        //propiedades.repaint(); //llamar al metodo repaint
    //propiedades.revalidate(); //llamar al metodo revalidate si se han añadido o eliminado componentes
    repaint();
    revalidate();
    this.setVisible(true);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Saldo = new javax.swing.JLabel();
        Espc = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        Especulador = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        propiedadesPanel = new javax.swing.JPanel();

        Nombre.setText("Nombre");

        Saldo.setText("Saldo");

        Espc.setText("Especulador");

        nombre.setEditable(false);
        nombre.setText("Nombre");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        saldo.setEditable(false);
        saldo.setText("Saldo");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });

        Especulador.setEditable(false);
        Especulador.setText("Especulador");
        Especulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspeculadorActionPerformed(evt);
            }
        });

        propiedadesPanel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Saldo)
                        .addGap(81, 81, 81)
                        .addComponent(Espc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(propiedadesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(Saldo)
                    .addComponent(Espc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(146, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(propiedadesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EspeculadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspeculadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspeculadorActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Espc;
    private javax.swing.JTextField Especulador;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Saldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
