/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.CasillaCalle;
/**
 *
 * @author Luis
 */
public class PropiedadPanel extends javax.swing.JPanel {
    CasillaCalle tituloPropiedad;
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    void setPropiedad(CasillaCalle propiedad){ //ANTES CasillaCalle tituloPropiedad
        this.tituloPropiedad= propiedad; //= tiruloPropiedad
     //Nombre.setText("Nombre: ");
        //NumCasas.setText("Numero de Casas: ");
       // NumHoteles.setText("Numoero de Hoteles: ");
    //   esSostenible.setSelected(tituloPropiedad.soySostenible());
        this.valorNombre.setText(propiedad.getNombre());
        System.out.println(tituloPropiedad.toString());
        this.numCasas.setText(String.valueOf(propiedad.getNumCasas()));
        this.numeroHoteles.setText(String.valueOf(propiedad.getNumHoteles()));
        this.TextPrecioAlquiler.setText(String.valueOf(tituloPropiedad.getPrecioAlquilerCompleto()));
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        NumCasas = new javax.swing.JLabel();
        numCasas = new javax.swing.JTextField();
        PrecioAlquiler = new javax.swing.JLabel();
        TextPrecioAlquiler = new javax.swing.JTextField();
        valorNombre = new javax.swing.JTextField();
        numeroHoteles = new javax.swing.JTextField();
        NumHoteles = new javax.swing.JLabel();

        Nombre.setText("Propiedad");

        NumCasas.setText("Número Casas");

        numCasas.setText("numero casas");
        numCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numCasasActionPerformed(evt);
            }
        });

        PrecioAlquiler.setText("PrecioAlquiler");

        TextPrecioAlquiler.setEditable(false);
        TextPrecioAlquiler.setText("TextPrecioAlquiler");
        TextPrecioAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrecioAlquilerActionPerformed(evt);
            }
        });

        valorNombre.setText("nombre");
        valorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorNombreActionPerformed(evt);
            }
        });

        numeroHoteles.setText("numero hoteles");
        numeroHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroHotelesActionPerformed(evt);
            }
        });

        NumHoteles.setText("NumHoteles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(Nombre)
                                .addGap(188, 188, 188))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valorNombre)
                                .addGap(118, 118, 118)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumCasas)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(NumHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(PrecioAlquiler))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(numeroHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(NumCasas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioAlquiler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        valorNombre.setEditable(false);
    }// </editor-fold>//GEN-END:initComponents

    private void numCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numCasasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numCasasActionPerformed

    private void TextPrecioAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrecioAlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrecioAlquilerActionPerformed

    private void valorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorNombreActionPerformed

    private void numeroHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroHotelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroHotelesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NumCasas;
    private javax.swing.JLabel NumHoteles;
    private javax.swing.JLabel PrecioAlquiler;
    private javax.swing.JTextField TextPrecioAlquiler;
    private javax.swing.JTextField numCasas;
    private javax.swing.JTextField numeroHoteles;
    private javax.swing.JTextField valorNombre;
    // End of variables declaration//GEN-END:variables
}
